name: Kennyswork
favicon: null
layout_spectrum: 0.12822099239565432
typography_spectrum: 0.23545396351255476
title: Kennys work
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5a6aa'
    - '#7b796c'
    - '#dde7f1'
    - '#918f82'
    - '#453c37'
  brandStrength: 0.25
  lightness: 0.9623305010609329
  saturation: 0.6641487758606672
  rhythmicContrast: 0.07649769447743893
purpose: []
